# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e4d4cb2e775b70276d9161a403cee7f85a4440bd17cd8c1c6f13cbf7b399a58afed0e280004398a0af6f27626bcb9dbb689bde2f27ec4413e0e78f015df16d6

test:
  secret_key_base: 4e44ff732fa87e8d6e879a1c596f67dd64249835eb9667d848b4760dc3abfba1300282f94b75de358c831d41d9491b53eb74a5150b63778a67620961a06007e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
